/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

package org.mule.modules.box.model;

import javax.xml.bind.annotation.XmlElement;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.mule.modules.box.model.descriptor.EntityDescriptor;
import org.mule.modules.box.model.descriptor.UserDescriptor;

/**
 *
 * Comments are messages generated by Box users.
 * Each message is tied to specific files or discussions.
 * You can create comments independently or create them as responses to other comments.
 * 
 * @author mariano.gonzalez@mulesoft.com
 */
@JsonIgnoreProperties(ignoreUnknown=true)
public class Comment extends EntityDescriptor {

	private static final long serialVersionUID = 7670402222846957689L;
	
	/**
	 * Whether or not this comment is a reply to another comment
	 */
	private boolean isReplyComment;
	
	/**
	 * The comment text that the user typed
	 */
	private String message;
	
	/**
	 * The string representing the comment text with @mentions included.
	 * @mention format is @[id:username]. Field is not included by default.
	 */
	private String taggedMessage;
	
	/**
	 *  object representing the author of the comment
	 */
	private UserDescriptor createdBy;
	
	/**
	 * The time this comment was created
	 */
	private String createdAt;
	
	/**
	 * The object this comment was placed on
	 */
	private Item item;
	
	/**
	 * The time this comment was last modified
	 */
	private String modifiedAt;
	
	@XmlElement(name="is_reply_comment")
	public boolean isReplyComment() {
		return isReplyComment;
	}
	public void setReplyComment(boolean isReplyComment) {
		this.isReplyComment = isReplyComment;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	
	@XmlElement(name="created_by")
	public UserDescriptor getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(UserDescriptor createdBy) {
		this.createdBy = createdBy;
	}
	
	@XmlElement(name="created_at")
	public String getCreatedAt() {
		return createdAt;
	}
	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}
	public Item getItem() {
		return item;
	}
	public void setItem(Item item) {
		this.item = item;
	}
	
	@XmlElement(name="modified_at")
	public String getModifiedAt() {
		return modifiedAt;
	}
	public void setModifiedAt(String modifiedAt) {
		this.modifiedAt = modifiedAt;
	}
	
	@XmlElement(name="tagged_message")
	public String getTaggedMessage() {
		return taggedMessage;
	}
	public void setTaggedMessage(String taggedMessage) {
		this.taggedMessage = taggedMessage;
	}
}
