/**
 * Copyright (c) MuleSoft, Inc. All rights reserved. http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.md file.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.box;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Formatter;

import javax.inject.Inject;
import javax.ws.rs.core.MediaType;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.mule.DefaultMuleMessage;
import org.mule.api.MuleContext;
import org.mule.api.MuleException;
import org.mule.api.MuleMessage;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.lifecycle.Start;
import org.mule.api.annotations.lifecycle.Stop;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.mule.api.context.MuleContextAware;
import org.mule.commons.jersey.JerseyUtil;
import org.mule.construct.Flow;
import org.mule.modules.box.jersey.AuthBuilderBehaviour;
import org.mule.modules.box.jersey.BoxResponseHandler;
import org.mule.modules.box.jersey.MediaTypesBuilderBehaviour;
import org.mule.modules.box.model.Entries;
import org.mule.modules.box.model.Folder;
import org.mule.modules.box.model.FolderItems;
import org.mule.modules.box.model.SharedLink;
import org.mule.modules.box.model.descriptor.FolderItem;
import org.mule.modules.box.model.request.CopyFolderRequest;
import org.mule.modules.box.model.request.CreateFolderRequest;
import org.mule.modules.box.model.request.CreateSharedLinkRequest;
import org.mule.modules.box.model.request.RestoreTrashedFolderRequest;
import org.mule.modules.box.model.request.UpdateFolderRequest;
import org.mule.modules.box.model.response.GetAuthTokenResponse;
import org.mule.modules.box.model.response.GetTicketResponse;
import org.mule.modules.box.model.response.UploadFileResponse;
import org.mule.modules.boxnet.callback.AuthCallbackAdapter;

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.api.client.WebResource.Builder;
import com.sun.jersey.api.client.config.ClientConfig;
import com.sun.jersey.api.client.config.DefaultClientConfig;
import com.sun.jersey.api.json.JSONConfiguration;
import com.sun.jersey.core.impl.provider.entity.FormMultivaluedMapProvider;
import com.sun.jersey.core.impl.provider.entity.FormProvider;
import com.sun.jersey.core.impl.provider.entity.InputStreamProvider;
import com.sun.jersey.core.impl.provider.entity.MimeMultipartProvider;
import com.sun.jersey.multipart.FormDataMultiPart;
import com.sun.jersey.multipart.file.StreamDataBodyPart;
import com.sun.jersey.multipart.impl.MultiPartWriter;

/**
 * Box Cloud Connector for API V2.
 * 
 * @author mariano.gonzalez@mulesoft.com
 */
@Connector(name="box", schemaVersion="2.0", friendlyName="Box", minMuleVersion="3.3")
public class BoxConnector implements MuleContextAware {
    
	private static final Logger logger = Logger.getLogger(BoxConnector.class);
	
	private static final String BOX_AUTH_TICKET = "boxAuthTicket";
	private static final String BOX_AUTH_TOKEN = "boxAuthToken";
	
	private Client client;
	
	private MuleContext muleContext;
	private AuthCallbackAdapter authCallback;
	
    
	/**
	 * The api's base url
	 */
	@Configurable
	@Optional
	@Default("https://api.box.com/2.0/")
	private String baseUrl;
	
	/**
	 * The url where the user needs to enter his credentials
	 */
	@Configurable
	@Optional
	@Default("https://www.box.com/api/1.0/rest")
	private String authUrl;
	
	/**
     * The API key obtained when registering a project with the Box platform.
     * For more information about this field please refer to {@link http://developers.box.net/}
     */
    @Configurable
    private String apiKey;
    
    /**
     * If true, an http inbound endpoint will be set in place to receive a callback
     * from box.net with the authToken once the user has authenticated.
     * 
     * If this callback is in place, there's no need for you to manually
     * invoke the get-auth-token processor.
     * 
     * For more info look at http://developers.box.net/w/page/12923915/ApiAuthentication
     * 
     * Defaults to false
     */
    @Optional
    @Configurable
    @Default("false")
    private boolean usesCallback = false;
    
    
    /**
     * The url where box.net will direct the authentication callback.
     * For more info look at http://developers.box.net/w/page/12923915/ApiAuthentication
     * 
     * Defaults to box_auth_callback
     */
    @Optional
    @Configurable
    @Default("box_auth_callback")
    private String callbackPath = "box_auth_callback";
   
    /**
     * The port where the authentication callback will be listening on
     * Defaults to 8080
     */
    @Optional
    @Configurable
    @Default("8080")
    private Integer callbackPort;
    
    /**
     * The name of a flow to be executed each time the authentication token
     * needs to be used. If this attribute is specified, 	then a flow with this named
     * will be fetch on the registry and invoked every time the auth token is needed.
     * This flow will receive a copy of the current mule message and must set the payload
     * to a valid auth token. If the flow fails to accomplish that, an exception will be thrown
     * 
     * For example:
     * 
     * &lt;box:config apiKey="${apiKey}" restoreAuthTokenFlow="restoreTokenFlow" saveAuthTokenFlow="saveTokenFlow"/&gt;
     * 
     *  &lt;flow name="restoreTokenFlow"&gt;
     *		&lt;objectstore:retrieve key="flowVars['currentUserId']"/&gt;
     *	&lt;/flow&gt;
     *
     *	&lt;flow name="save"&gt;
     *		&lt;objectstore:store key="flowVars['currentUserId']" value-ref="#[flowVars['boxAuthToken']]"/&gt;
     *	&lt;/flow&gt;
     *
     *	If this attribute is not specified, then the token will be fetched from memory. Notice that this means the token won't survive
     * an application restart and that the connector would be incapable of handling two different concurrent accounts
     */
    @Configurable
    @Optional
    private String restoreAuthTokenFlow;
    
    /**
     * The name of a flow to be executed each time an authentication token
     * is received. If this attribute is specified, then a flow with this name
     * will be fetch on the registry and invoked every time the auth token is obtained.
     * This flow will receive a copy of the current mule message carrying two additional invocation variables:
     * 
     * <ul>
     * 	<li>boxAuthTicket: The ticket for which the authorization token was generated</li>
     * 	<li>boxAuthToken: The obtained authorization token
     * </ul>
     * 
     * For example:
     * 
     * &lt;box:config apiKey="${apiKey}" restoreAuthTokenFlow="restoreTokenFlow" saveAuthTokenFlow="saveTokenFlow"/&gt;
     * 
     *  &lt;flow name="restoreTokenFlow"&gt;
     *		&lt;objectstore:retrieve key="flowVars['currentUserId']"/&gt;
     *	&lt;/flow&gt;
     *
     *	&lt;flow name="save"&gt;
     *		&lt;objectstore:store key="flowVars['currentUserId']" value-ref="#[flowVars['boxAuthToken']]"/&gt;
     *	&lt;/flow&gt;
     *
     * If this attribute is not specified, then the token will be stored in memory. Notice that this means the token won't survive
     * an application restart and that the connector would be incapable of handling two different concurrent accounts
     */
    @Configurable
    @Optional
    private String saveAuthTokenFlow;
    
    /**
     * The name of a flow to be invoked after an authorization callback is received.
     * If {@link usesCallback} is false then this flow will never be invoked.
     * 
     * This flow will receive a copy of the current mule message carrying two additional invocation variables:
     * 
     * <ul>
     * 	<li>boxAuthTicket: The ticket for which the authorization token was generated</li>
     * 	<li>boxAuthToken: The obtained authorization token
     * </ul>
     * 
     * For example:
     * 
     * &lt;box:config apiKey="${apiKey}" restoreAuthTokenFlow="restoreTokenFlow" saveAuthTokenFlow="saveTokenFlow"/&gt;
     * 
     *  &lt;flow name="restoreTokenFlow"&gt;
     *		&lt;objectstore:retrieve key="flowVars['currentUserId']"/&gt;
     *	&lt;/flow&gt;
     *
     *	&lt;flow name="save"&gt;
     *		&lt;objectstore:store key="flowVars['currentUserId']" value-ref="#[flowVars['boxAuthToken']]"/&gt;
     *	&lt;/flow&gt;
     * 
     * This flow will receive the same mule message the auth callback receives. If additionaly you also
     * provided a saveAuthTokenFlow, then any mutations done to the message there are also available in this flow
     */
    @Configurable
    @Optional
    private String postAuthFlow;
    
    /**
     * The http connector to be used when serving the authorization callback.
     * If {@link usesCallback} is false then this connector is not used.
     * 
     * If not provided, the default http connector under the key 'connector.http.mule.default' will be used.
     * However, specifying an https connector is adviced. 
     */
    @Configurable
    @Optional
    private org.mule.api.transport.Connector httpConnector;
    
    /**
     * Actual restore token flow egarly fetched
     */
    private Flow restoreTokenFlow;
    
    /**
     * Actual save token flow egarly fetched
     */
    private Flow saveTokenFlow;
    
    private Flow postAuthorizationFlow;
    
    private String authToken;
    
    private JerseyUtil jerseyUtil;
    
    private WebResource apiResource;
    
    private WebResource authResource;
    
    /**
     * This method initiaes the box client and the auth callback.
     * Also, it fetches the save/restore flows (if specified). If those are specified
     * but don't exist in the registry, then IllegalArgumentException is thrown
     * 
     * @throws MuleException
     * @throws IllegalArgumentException if restore/save token flows are specified but don't exist
     */
    @Start
    public void init() throws MuleException {
    	ClientConfig clientConfig = new DefaultClientConfig();
    	clientConfig.getFeatures().put(JSONConfiguration.FEATURE_POJO_MAPPING, Boolean.TRUE);
    	clientConfig.getClasses().add(MultiPartWriter.class);
    	clientConfig.getClasses().add(MimeMultipartProvider.class);
    	clientConfig.getClasses().add(InputStreamProvider.class);
    	clientConfig.getClasses().add(FormProvider.class);
    	clientConfig.getClasses().add(FormMultivaluedMapProvider.class);
    	
    	this.client = Client.create(clientConfig);
    	
    	this.authCallback = new AuthCallbackAdapter(this.muleContext, this);
		this.authCallback.setLocalPort(this.getCallbackPort());
		this.authCallback.setAsync(false);

		if (this.usesCallback) {
			this.postAuthorizationFlow = this.fetchFlow(this.postAuthFlow);
			this.authCallback.start();
    	}
		
		this.restoreTokenFlow = this.fetchFlow(this.restoreAuthTokenFlow);
		this.saveTokenFlow = this.fetchFlow(this.saveAuthTokenFlow);
		
		this.initJerseyUtil();
		
		this.apiResource = this.client.resource(this.baseUrl);
		this.authResource = this.client.resource(this.authUrl);
    }
    
    private void initJerseyUtil() {
    	this.jerseyUtil = JerseyUtil.builder()
    						.addRequestBehaviour(MediaTypesBuilderBehaviour.INSTANCE)
    						.addRequestBehaviour(new AuthBuilderBehaviour(this))
    						.setResponseHandler(BoxResponseHandler.INSTANCE)
    						.build();
    }
    
    @Stop
    public void onStop() throws MuleException {
    	if (this.usesCallback) {
    		this.authCallback.stop();
    	}
    }
    
    
    /**
     * Get and access ticket using the configured apiKey. Optionally, you can ask the connector to automatically
     * redirect the browser to box authorization page so that the user can enter his credentials. This is done
     * by invoking {@link org.mule.modules.box.BoxConnector.authorizeTicket(MuleMessage, String)}
     * 
     * Otherwise, the user needs to manually go to {@link https://www.box.com/api/1.0/auth/&lt;&lt;ticket&gt;&gt;}
     * 
     * Either way, the connector <b>WILL NOT</b> be responsible for storing this ticket.
     * 
     * For more info look at {@link http://developers.box.com/get-started/}
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:get-ticket}
     * 
     * @param message the current mule message
     * @param redirect if true, then the browser will be automatically redirected to https://www.box.net/api/1.0/auth/&lt;&lt;ticket&gt;&gt;
     *  
     * @return the obtained ticket
     */
    @Processor
    @Inject
    public String getTicket(MuleMessage message, @Optional @Default("true") Boolean redirect) {
    	
    	GetTicketResponse response = this.authResource
						    			.queryParam("action", "get_ticket")
						    			.queryParam("api_key", this.apiKey)
							    		.accept(MediaType.APPLICATION_XML)
							    		.get(GetTicketResponse.class);
    	if (response.isValid()) {
    		
    		String ticket = response.getTicket();
    		
    		if (logger.isDebugEnabled()) {
    			logger.debug(String.format("Fetched ticket with apiKey %s and obtained %s", this.apiKey, ticket));
    		}

    		if (redirect) {
    			this.authorizeTicket(message, ticket);
    		}
    		
    		return ticket;
    	
    	} else {
    		throw new RuntimeException(String.format("Failed to obtain ticket. Box response was %s", response.getStatus()));
    	}
    	
    }
    
    /**
     * Redirects the browser to box authorization page so that the user can enter his credentials.
     * The new location will be {@link https://www.box.net/api/1.0/auth/&lt;&lt;ticket&gt;&gt;}
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:authorize-ticket}
     * 
     * @param message the current mule message
     * @param ticket the ticket to be authorized
     */
    @Processor
    @Inject
    public void authorizeTicket(MuleMessage message, String ticket) {
    	String redirectUrl = "https://www.box.com/api/1.0/auth/" + ticket;
    	
    	if (logger.isDebugEnabled()) {
    		logger.debug(String.format("redirecting to %s for authorizing ticket %s", redirectUrl, ticket));
    	}
    	
    	message.setOutboundProperty("http.status", "302");
    	message.setOutboundProperty("Location", redirectUrl);
    }

    /**
     * After the user authenticates the ticket obtained with the get-ticket processor,
     * there're two ways to get the required auth token:
     * 
     * <ol>
	 *	<li>
	 *		You can configure box.net to make a callback returning the ticket and authToken, in which case you need to set the
	 * 		usesCallback and callbackPath config attributes accordingly 
	 *	</li>
	 *	<li>
	 *		You can use this processor to obtain the authentication token explicitly.
	 *  </li>
	 *	</ol>
	 *
	 *  Either way, this connector will retain the authToken in memory and will use it in all operations.
	 *  
	 *  For more info look at http://developers.box.net/w/page/12923915/ApiAuthentication
     *
     * {@sample.xml ../../../doc/box-connector.xml.sample box:auth-token}
     *
     * @param message the current mule message
     * @param ticket the ticket to authenticate against.
     * @return an instance of {@link org.mule.modules.box.model.response.GetAuthTokenResponse} with information about the current user
     * @throws IllegalArgumentException if the ticket does not match a logged user
     */
    @Processor
    @Inject
    public GetAuthTokenResponse authToken(MuleMessage message, String ticket) {
    	

    	GetAuthTokenResponse response = this.authResource
							    			.queryParam("action", "get_auth_token")
							    			.queryParam("api_key", this.apiKey)
							    			.queryParam("ticket", ticket)
								    		.accept(MediaType.APPLICATION_XML)
								    		.get(GetAuthTokenResponse.class); 
    	
    	if (response.isNotLoggedIn()) {
    		String msg = "Failed to obtain authToken using ticket " + ticket + ". Not logged in";
       	 	logger.error(msg);
       	 	throw new IllegalStateException(msg);
    	}
    	
    	if (response.isValid()) {
    		String authToken = response.getAuthToken();
    		
    		if (logger.isDebugEnabled()) {
    			logger.debug(String.format("ticket %s mapped to authToken: %s", ticket, authToken));
    		}
    		
    		this.saveAuthToken(message, ticket, authToken);
    		return response;
    		
    	} else {
    		throw new RuntimeException(String.format("Status %s was obtained while fetching access token", response.getStatus()));
    	}
    }

    /**
     * Retrieves information about a given folder. If the folderId parameter is not
     * provided or equals 0, then the root folder will be returned.
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:get-folder}
     * 
     * @param message the current mule message
     * @param folderId the id of the fodler you want to get. 0 means root
     * @return an instance of {@link org.mule.modules.box.model.Folder}
     */
    @Processor
    @Inject
    public Folder getFolder(MuleMessage message, @Optional @Default("0") String folderId) {
    	return this.jerseyUtil.get(this.apiResource.path("folders").path(folderId), Folder.class, 200);
    }
    
    /**
     * Creates a new folder and returns a folder object with all its associated information
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:create-folder}
     * 
     * @param message the current mule message
     * @param parentId the id of the parent folder. If not provided then the root will be used
     * @param folderName the name of the folder
     * @return an instance of {@link org.mule.modules.box.model.Folder} representing the newly created folder
     */
    @Processor
    @Inject
    public Folder createFolder(MuleMessage message, @Optional @Default("0") String parentId, String folderName) {
    	return this.jerseyUtil.post(this.apiResource.path("folders")
    							.entity(new CreateFolderRequest(folderName, parentId)),
	    						Folder.class,
	    						200, 201);
    }
    
    
    /**
     * Used to update information about the folder. To move a folder, update the ID of its parent.
     * To enable an email address that can be used to upload files to this folder, update the folderUploadEmail attribute.
     * An optional If-Match header can be included to ensure that client only updates the folder if it knows about the latest version by setting the etag attribute.
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:update-folder}
     * 
     * @param message the current mule message
     * @param request an instance of {@link org.mule.modules.box.model.request.UpdateFolderRequest} with the attributes you want to change
     * @param folderId the id of the folder to be modified
     * @param etag if provided, it will be used to verify that no newer version of the file is available at box
     * @return an instance of {@link org.mule.modules.box.model.Folder} that represents the updated folder
     */
    @Processor
    @Inject
    public Folder updateFolder(MuleMessage message, @Optional @Default("#[payload]") UpdateFolderRequest request, String folderId, @Optional String etag) {
    	WebResource resource = this.apiResource.path("folders").path(folderId);
    	return this.jerseyUtil.put(this.maybeAddIfMacth(resource, etag), Folder.class, 200, 201);
    }
    
    /**
     * Retrieves the discussions on a particular folder, if any exist.
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:get-folder-discussions}
     * 
     * @param message the current mule message
     * @param folderId the id of the folder which discussions  you want
     * @return an instance of {@link org.mule.modules.box.model.Entries}
     */
    @Processor
    @Inject
    public Entries getFolderDiscussions(MuleMessage message, String folderId) {
    	return this.jerseyUtil.get(this.apiResource.path("folders").path(folderId).path("discussions"), Entries.class, 200, 204);
    }
    
    /**
     * Get the Items in the Trash. Retrieves the files and/or folders that have been moved to the trash using the mini format.
     * Paginated results can be retrieved using the limit and offset parameters.

     * {@sample.xml ../../../doc/box-connector.xml.sample box:get-trashed-items}
     * 
     * @param message the current mule message
     * @param limit the maximum amount of items to be returned (default=100, max=1000)
     * @param offset pagination offset (default=0)
     * @return an instance of {@link org.mule.modules.box.model.FolderItems}
     */
    @Processor
    @Inject
    public FolderItems getTrashedItems(MuleMessage message, @Optional @Default("100") Long limit, @Optional @Default("0") Long offset) {
    	return this.getFolderItems(message, "trash", limit, offset);
    }
    
    /**
     * Restores an item that has been moved to the trash. Default behavior is to restore the item to the folder it was in before it was moved to the trash.
     * If that parent folder no longer exists or if there is now an item with the same name in that parent folder,
     * the new parent folder and/or new name will need to be included in the request.
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:restore-trashed-folder}
     * 
     * @param message the current mule message
     * @param folderId the id of the trashed folder being restored
     * @param request an instance of {@link org.mule.modules.box.model.request.RestoreTrashedFolderRequest} with the request parameters
     * @return an instance of {@link org.mule.modules.box.model.Folder} with the restored folder new state
     */
    public Folder restoreTrashedFolder(MuleMessage message, String folderId, @Optional @Default("#[payload]") RestoreTrashedFolderRequest request) {
    	return this.jerseyUtil.post(this.apiResource
	    								.path("folders")
	    								.path(folderId)
	    								.entity(request)
    								, Folder.class
    								, 201);
    }
    
    /**
     * Permanently deletes an item that is in the trash. The item will no longer exist in Box. This action cannot be undone.
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:perm-delete-folder}
     * 
     * @param folderId the id of the folder to be permanently deleted
     */
    @Processor
    public void permDeleteFolder(String folderId) {
    	this.jerseyUtil.delete(this.apiResource.path("folders").path(folderId).path("trash"), String.class, 204);
    }
    
    /**
     * Used to create a shared link for this particular folder
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:share-folder}
     * 
     * @param message the current mule message
     * @param folderId the id of the folder you want to share
     * @param sharedLink an instance of {@link org.mule.modules.box.model.SharedLink} with the information about the share
     * @return an instance of {@link org.mule.modules.box.model.Folder} representing the shared folder
     */
    @Processor
    @Inject
    public Folder shareFolder(MuleMessage message, String folderId, @Optional @Default("#[payload]") SharedLink sharedLink) {
    	CreateSharedLinkRequest request = new CreateSharedLinkRequest();
    	request.setSharedLink(sharedLink);
    	
    	return this.jerseyUtil.put(this.apiResource.path("folders")
    								.path(folderId)
	    							.entity(request),
	    						Folder.class,
	    						200, 201);
    }
    
    /**
     * Deletes the shared link associated to a folder
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:unshare-folder}
     * 
     * @param message the current mule message
     * @param folderId the id of the folder you want to unshare
     * @return an instance of {@link org.mule.modules.box.model.Folder} representing the unshared folder
     */
    @Processor
    @Inject
    public Folder unshareFolder(MuleMessage message, String folderId) {
    	return this.shareFolder(message, folderId, null);
    }
    
    /**
     * Used to create a shared link for this particular folder
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:share-folder}
     * 
     * @param message the current mule message
     * @param parentId the id of the parent folder that will hold the copy. If not provided then the root will be used
     * @param folderId the if od the folder being copied
     * @return an instance of {@link org.mule.modules.box.model.Folder} representing the copy
     */
    @Processor
    @Inject
    public Folder copyFolder(MuleMessage message, @Optional @Default("0") String parentId, String folderId) {
    	return this.jerseyUtil.post(this.apiResource.path("folders")
    								.path(folderId)
    								.path("copy")
	    							.entity(new CopyFolderRequest(parentId)),
	    						Folder.class,
	    						200, 201);
    }
    
    
    
    
    /**
     * Retrieves the files and/or folders contained within this folder without any other metadata about the folder in the mini format is returned for each item by default.
     * Paginated results can be retrieved using the limit and offset parameters.
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:get-folder-items}
     * 
     * @param message the current mule message
     * @param folderId the id of the folder you want to inspect. If not provided then the root folder is assumed
     * @param limit the maximum amount of items to be returned (default=100, max=1000)
     * @param offset pagination offset (default=0)
     * @return an instance of {@link org.mule.modules.box.model.FolderItems}
     */
    @Processor
    @Inject
    public FolderItems getFolderItems(
    					MuleMessage message,
    					@Optional @Default("0") String folderId,
    					@Optional @Default("100") Long limit,
    					@Optional @Default("0") Long offset) {
    	WebResource resource = this.apiResource
						    			.path("folders")
						    			.path(folderId)
						    			.path("items");
    	
    	if (offset != null) {
    		resource = resource.queryParam("offset", offset.toString());
    	}
    	
    	if (limit != null) {
    		resource = resource.queryParam("limit", limit.toString());
    	}
    	
    	return this.jerseyUtil.get(resource, FolderItems.class, 200);
    }
    
    /**
     * Traverses a given folder looking for a resource (file or folder) of a given name.
     *  
     * {@sample.xml ../../../doc/box-connector.xml.sample box:get-folder-item}
     * 
     * @param message the current mule message
     * @param folderId the id of the folder you want to inspect. If not provided then the root folder is assumed
     * @param resourceName the name you want to test
     * @return an instance of {@link org.mule.modules.box.model.descriptor.FolderItem} with that about the found item. {@code null} if the item is not found
     */
    @Processor
    @Inject
    public FolderItem getFolderItem(MuleMessage message, @Optional @Default("0") String folderId, String resourceName) {
    	FolderItems items = this.getFolderItems(message, folderId, null, null);
    	
    	for (FolderItem item : items.getEntries()) {
    		if (resourceName.equals(item.getName())) {
    			return item;
    		}
    	}
    	
    	return null;
    }
    
    /**
     * Deletes a folder
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:delete-folder}
     * 
     * @param message the current mule message
     * @param folderId the id of the folder to be deleted
     * @param recursive Whether to delete this folder if it has items inside of it
     */
    @Processor
    @Inject
    public void deleteFolder(MuleMessage message, String folderId, @Optional @Default("true") Boolean recursive) {
    	this.jerseyUtil.delete(
    			this.apiResource
    				.path("folders")
    				.path(folderId)
    				.queryParam("recursive", recursive.toString())
    			, String.class, 200, 204);
    			
    	
    }
    
    /**
     * Creates a new file with the contents of a {@link java.io.InputStream}.
     * You need to take in count that since this is a stream, using the option of including a verification hash
     * will cause the contents of the input stream to be fully read and loaded in memory. 
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:upload-stream}
     * 
     * @param message the current mule message
     * @param folderId the id of the target folder.
     * @param filename the name you want the file to have at box.
     * @param content a {@link java.io.InputStream} with the contents of the file. This processor <b>IS NOT</b> responsible for closing it
     * @param includeHash if true a sha1 hash of the file will be calculated prior to upload. Box will use that hash
     * 			to verify that the content's hasn't been corrupted.
     * @param contentCreatedAt The time this file was created on the user’s machine. An example of a valid date is 2012-12-12T10:55:30-08:00
     * @param contentModifiedAt The time this file was modified on the user’s machine. An example of a valid date is 2012-12-12T10:55:30-08:00
     * @return an instance of {@link org.mule.modules.box.model.File} with the information of the created file
     */
    @Processor
    @Inject
    public UploadFileResponse uploadStream(
    		MuleMessage message,
    		@Optional @Default("0") String folderId,
    		String filename,
    		@Optional @Default("#[payload]") InputStream content,
    		@Optional @Default("false") boolean includeHash,
    		@Optional String contentCreatedAt,
    		@Optional String contentModifiedAt) {
    	
    	WebResource.Builder resource = this.apiResource.path("files").path("content").type(MediaType.MULTIPART_FORM_DATA);
    	
    	if (includeHash) {
			resource.header("Content-MD5", this.hash(content));
    	}
    	
    	FormDataMultiPart form = new FormDataMultiPart();
		form.field("parent_id", folderId);
		
		if (!StringUtils.isBlank(contentCreatedAt)) {
			form.field("content_created_at", contentCreatedAt);
		}
		
		if (!StringUtils.isBlank(contentModifiedAt)) {
			form.field("content_modified_at", contentModifiedAt);
		}
		
		form.bodyPart(new StreamDataBodyPart(filename, content));
		
    	resource.entity(form);
    	
    	return this.jerseyUtil.post(resource, UploadFileResponse.class, 200, 201);
    }
    
    private String hash(InputStream content) {
    	byte[] bytes = null;
		try {
			bytes = IOUtils.toByteArray(content);
		} catch (IOException e) {
			throw new RuntimeException("Error generating sha1 for content", e);
		}
		
		Formatter formatter = new Formatter();
		try {
			for (byte b : bytes) {
				formatter.format("%02x", b);
			}
			return formatter.toString();
		} finally {
			formatter.close();
		}
    }
    
    /**
     * Receives the path of a file in local storage and uploads its content
     *
     * {@sample.xml ../../../doc/box-connector.xml.sample box:upload-path}
     * 
     * @param message the current mule message
     * @param path the path of the file in local storage
     * @param folderId the id of the target folder.
     * @param filename the name you want the file to have at box. If not provided, the name on current storage will be used
     * @param includeHash if true a sha1 hash of the file will be calculated prior to upload. Box will use that hash
     * 			to verify that the content's hasn't been corrupted. 
     * @param contentCreatedAt The time this file was created on the user’s machine. An example of a valid date is 2012-12-12T10:55:30-08:00
     * @param contentModifiedAt The time this file was modified on the user’s machine. An example of a valid date is 2012-12-12T10:55:30-08:00
     * 
     * @return an instance of {@link org.mule.modules.box.model.File} with the information of the created file
     */
    @Processor
    @Inject
    public UploadFileResponse uploadPath(
    		MuleMessage message,
    		String path, 
    		@Optional @Default("0") String folderId,
    		@Optional String filename,
    		@Optional @Default("false") boolean includeHash,
    		@Optional String contentCreatedAt,
    		@Optional String contentModifiedAt) {
    	
    	
		java.io.File file = new java.io.File(path);
    		
		if (!file.exists()) {
			throw new IllegalArgumentException(String.format("File %s does not exist", path));
		}
		
		if (StringUtils.isBlank(filename)) {
			filename = file.getName();
		}
    	
		byte[] content = null;
		
		try {
			FileUtils.readFileToByteArray(file);
		} catch (IOException e) {
			throw new RuntimeException(String.format("Error reading file at %s", path), e);
		}
		
		return this.uploadStream(message, folderId, filename,
								new ByteArrayInputStream(content), includeHash,
								contentCreatedAt, contentModifiedAt);
    }
    
    /**
     * Deletes a file
     * 
     * {@sample.xml ../../../doc/box-connector.xml.sample box:delete-file}
     * 
     * @param message the current mule message
     * @param fileId the id of the file to be deleted
     * @param etag if provided, it will be used to verify that no newer version of the file is available at box
     */
    @Processor
    @Inject
    public void deleteFile(MuleMessage message, String fileId, @Optional String etag) {
    	WebResource resource = this.apiResource.path("files").path(fileId);
    	this.jerseyUtil.delete(this.maybeAddIfMacth(resource, etag), String.class, 200, 204);
    }
    

    public String getAuthToken(MuleMessage message) {
    	String token = null;
    	
    	if (this.restoreTokenFlow == null) {
    	
    		token = this.authToken;
    	
    	} else {
    		MuleMessage restoreMessage = FlowUtils.callFlow(this.restoreTokenFlow, new DefaultMuleMessage(message)); 
    		Object payload = restoreMessage.getPayload();
    		
    		if (payload instanceof String) {
    			token = (String) payload;
    			return token;
    		} else {
    			throw new IllegalArgumentException(
    					String.format("A String payload was expected after invoking restore token flow '%s', but %s was found instead",
    							this.restoreAuthTokenFlow,
    							payload == null ? "null" : payload.getClass().getCanonicalName()
    							)
    					);
    		}
    	}
    	
    	if (StringUtils.isBlank(token)) {
    		throw new IllegalStateException("Auth token not obtained yet");
    	}
    	
    	return token;
    }
    
    private WebResource.Builder maybeAddIfMacth(WebResource resource, String etag) {
    	Builder builder = resource.getRequestBuilder();
    	
    	if (!StringUtils.isBlank(etag)) {
    		builder = builder.header("If-Match", etag);
    	}
    	
    	return builder;
    }
    
    private Flow fetchFlow(String flowname) {
    	if (StringUtils.isBlank(flowname)) {
    		return null;
    	}
    	
    	Flow flow = FlowUtils.getFlow(flowname, muleContext);
    	
    	if (flow == null) {
    		throw new IllegalArgumentException(String.format("flow %s doesn't exists", flowname));
    	}
    	
    	return flow;
    }
    
   public MuleMessage saveAuthToken(MuleMessage message, String ticket, String authToken) {
	   
	   if (StringUtils.isBlank(ticket)) {
		   throw new IllegalArgumentException("auth process did not return a ticket");
	   }
	   
	   if (StringUtils.isBlank(authToken)) {
		   throw new IllegalArgumentException("auth process did not return an auth token");
	   }
	   
	   MuleMessage copy = new DefaultMuleMessage(message);
	   copy.setInvocationProperty(BOX_AUTH_TICKET, ticket);
	   copy.setInvocationProperty(BOX_AUTH_TOKEN, authToken);
	   
	   if (this.saveTokenFlow == null) {
			this.authToken = authToken;
	   } else {
			FlowUtils.callFlow(this.saveTokenFlow, copy);
	   }
	   
	   this.postAuth(copy);
	   
	   return copy;
    }
   
   private void postAuth(MuleMessage message) {
	   if (this.postAuthorizationFlow != null) {
		   if (logger.isDebugEnabled()) {
			   logger.debug(String.format("invoking post authorization flow %s with message %s", this.postAuthFlow, message.toString()));
		   }
		   FlowUtils.callFlow(this.postAuthorizationFlow, message);
	   } else {
		   if (logger.isDebugEnabled()) {
			   logger.debug("No post auth flow specified");
		   }
	   }
   }
    
	public String getCallbackPath() {
		return callbackPath;
	}

	public void setCallbackPath(String callbackPath) {
		this.callbackPath = callbackPath;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}
	
	public Integer getCallbackPort() {
		return callbackPort;
	}

	public void setCallbackPort(Integer callbackPort) {
		this.callbackPort = callbackPort;
	}
	
	public boolean isUsesCallback() {
		return usesCallback;
	}

	public void setUsesCallback(boolean usesCallback) {
		this.usesCallback = usesCallback;
	}

	@Override
	public void setMuleContext(MuleContext context) {
		this.muleContext = context;
	}

	public String getRestoreAuthTokenFlow() {
		return restoreAuthTokenFlow;
	}

	public void setRestoreAuthTokenFlow(String restoreAuthTokenFlow) {
		this.restoreAuthTokenFlow = restoreAuthTokenFlow;
	}

	public String getSaveAuthTokenFlow() {
		return saveAuthTokenFlow;
	}

	public void setSaveAuthTokenFlow(String saveAuthTokenFlow) {
		this.saveAuthTokenFlow = saveAuthTokenFlow;
	}

	public String getApiKey() {
		return apiKey;
	}

	public org.mule.api.transport.Connector getHttpConnector() {
		return httpConnector;
	}

	public void setHttpConnector(org.mule.api.transport.Connector httpConnector) {
		this.httpConnector = httpConnector;
	}

	public String getPostAuthFlow() {
		return postAuthFlow;
	}

	public void setPostAuthFlow(String postAuthFlow) {
		this.postAuthFlow = postAuthFlow;
	}

	public String getBaseUrl() {
		return baseUrl;
	}

	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	public String getAuthUrl() {
		return authUrl;
	}

	public void setAuthUrl(String authUrl) {
		this.authUrl = authUrl;
	}
}
